### ISSUE TITLE
Revamp controller manager integration

### ISSUE THREAD

**Issue by faisal-memon** [spiffe/helm-charts-hardened#14] opened 2023-10-03 17:48 UTC
The current controller manager integration has a number of issues:
- The CRD and CRs are deployed together. This is problematic for CI/CD workflows.
- Other projects have the CRD as a seperate chart, installed separately
- Helm won't automatically upgrade if the controller-manager CRD changes. This could be possibly related to not versioning the controller manager CRD when it changes.

Original issue: https://github.com/spiffe/helm-charts/issues/427

**Comment by edwbuck** [comment] 2023-10-03 20:15
Ideally, the CRD should be versioned such that both version of the CRD can be deployed at the same time.

This permits one to have the old CRs lingering in the system while they are being migrated to the new CRD format, if such an upgrade support is needed.

A plan like this will require coordination with the SPIRE Controller Manager in the SPIRE project so the Controller Manager will check for all the supported CRD versions and shutdown if they are not present, and when they are present, will listen to all of the supported CRD versions.

The primary reason that the CRD is not being updated according to new versions of it is likely due to the Object Identifier ( apiVersion / kind / metadata.name / metadata.namespace ) not changing when the CRD's spec changes.  As Helm checks to see if the CRD was previously deployed, it finds a CRD with the same Object Identifier present, so it determines that an upgrade is not necessary.  In our scenario the old / new versions both have the same Object Identifier, but the spec sections change.  I do not believe that Helm is performing a deep comparison between the two items, as the spec section quickly wraps custom object (CR) definitions, which is where the relevant changes we want to apply are located.

**Comment by kfox1111** [comment] 2023-10-03 20:21
When using helm3 with the crds dir, helm only looks to see if the crd's metadata.name in each object in that dir already exists, and if not, applies that crd to the cluster. Very basic logic. So any update to the objects wont be applied at all. This was by design. Details at https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations

**Comment by kfox1111** [comment] 2023-10-04 00:25
The easiest solution would be to move the crds out to their own chart named something like spire-crds and put them in its template directory. Everyone would install/upgrade the crds chart first, then the main spire one. (Or use the raw crds manifests instead of the crds chart).

If we wanted to still have it work as just one chart to install/upgrade there are a couple options but both require helm hooks to function. so likely we'd still need the option of some users deploying two charts if they couldn't run helm hooks.

The two main variants would be:
1. helm pre hooks for installing/upgrading the crds. There are a lot of data to the crds so would be a little bit difficult to mash them in via a hook. opa gatekeeper builds a hook like this and has a special image with the crds baked into it along with kubectl. A drawback to that approach is as an end user you cant see what crds its going to upload very easily at all. I really like to helm diff and see what an upgrade is going to do.

2. helm post hook for installing/updating the ClusterSPIFFEID. We only have one of them, its a small object, and it very rarely changes. It also could simplify the other helm hooks as there are multiple to try and work around problems with the ClusterSPIFFEID not being usable until the spire-server is functional. With a job, it could init container wait-for-it on the spire-server coming up before kubectl applying the ClusterSPIFFEID removing the need to mess with webhook configurations at all. This might require a spire-clusterspiffeid chart instead of a spire-crds chart for those not wanting to run helm hooks.

**Comment by marcofranssen** [comment] 2023-10-04 06:59
3 possible options

1. Keep chart as is, install crds via `kubectl apply` and chart with `installCrds: false`
2. Move CRDs to separate Helm chart, Install both Helm charts
3. Add dependency on CRDs chart with a installCRDs value.
   This will be an extension of 2. that allows for optional management via the Helm Hooks to install CRDs first.

We can approach this in 3 PRs.

1. Document in README.md and release notes for upgrading to new version
2. Move CRDs to separate Chart + adjust documentation / release notes
3. Add the dependency on our spire chart with the optional flag to manage the CRDs

**Comment by kfox1111** [comment] 2023-10-04 15:43
@marcofranssen With your option one, we'd require users to kubectl apply the crds before upgrading the helm chart?

**Comment by kfox1111** [comment] 2023-10-04 16:39
@marcofranssen  what do you think of my option 2?

**Comment by faisal-memon** [comment] 2023-10-04 19:51
Reading through the discussion here brings up another issue for me: the actual clusterspiffeid. Should that be the separate chart? Thats what we interact with more. The CRD itself seems to me to be more in the realm of the statefulset, configmaps, etc. General plumbing we can hide.

Is it possible to keep the CRD in the same chart as a template so it gets updated with everything else? And then split the clusterspiffeid definition off into a separate chart. Then we can version that, add new fields as necessary.

**Comment by kfox1111** [comment] 2023-10-05 17:51
> Reading through the discussion here brings up another issue for me: the actual clusterspiffeid. Should that be the separate chart? Thats what we interact with more. The CRD itself seems to me to be more in the realm of the statefulset, configmaps, etc. General plumbing we can hide.
> 
> Is it possible to keep the CRD in the same chart as a template so it gets updated with everything else? And then split the clusterspiffeid definition off into a separate chart. Then we can version that, add new fields as necessary.

Yeah. That could be done.

**Comment by faisal-memon** [comment] 2023-10-09 19:04
@marcofranssen What do you think of my proposal?

**Comment by marcofranssen** [comment] 2023-10-10 08:45
> @marcofranssen What do you think of my proposal?

It sounds as an interesting approach to try. Although I don't fully understand what you are describing there, maybe you can give us a voice over.

**Comment by kfox1111** [comment] 2023-10-18 18:48
Fixed in https://github.com/spiffe/helm-charts-hardened/pull/8

**Closed by kfox1111** 2023-10-18 18:48 UTC
